<a href="https://colab.research.google.com/github/Pranayshukla0610/python-interview-mastery/blob/main/01_CSV_Data_Ingestion_and_Dataset_Understanding_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q pandas numpy openpyxl pyarrow sqlalchemy requests

| Library    | Purpose                     |
| ---------- | --------------------------- |
| pandas     | Data ingestion/manipulation |
| numpy      | Numerical operations        |
| openpyxl   | Excel                       |
| pyarrow    | Parquet                     |
| sqlalchemy | SQL databases               |
| requests   | APIs                        |

In [ ]:
import pandas as pd
import numpy as np

import json
import requests
import os
from pathlib import Path

from sqlalchemy import create_engine

In [ ]:
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 2.2.3
NumPy: 2.1.3

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ecommerce_sales_34500-selected-columns.csv to ecommerce_sales_34500-selected-columns.csv

In [ ]:
os.listdir()

['.config', 'ecommerce_sales_34500-selected-columns.csv', 'sample_data']

Read Kaggle CSV

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv')
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

UNDERSTANDING THE FILE SYSTEM

In [ ]:
os.getcwd()

'/content'

In [ ]:
os.listdir()

['.config', 'ecommerce_sales_34500-selected-columns.csv', 'sample_data']

In [ ]:
os.path.exists('/content/ecommerce_sales_34500-selected-columns.csv')

True

File Size

In [ ]:
file_size = os.path.getsize('/content/ecommerce_sales_34500-selected-columns.csv')
print(file_size)

2242283

In [ ]:
print("File Size:",file_size,"bytes")

File Size: 2242283 bytes

In [ ]:
file_size_mb = file_size / (1024 * 1024)
print("File Size:",file_size_mb,"MB")

File Size: 2.1384077072143555 MB

#CSV INGESTION

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv')

In [ ]:
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',encoding='utf-8')

In [ ]:
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',encoding='latin1')

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',encoding='cp1252')

Different files may use different character encodings.

A common error is:

UnicodeDecodeError

In [ ]:
encodings = [
    "utf-8",
    "latin1",
    "cp1252"
]

for encoding in encodings:

    try:

        df = pd.read_csv(
            "/content/ecommerce_sales_34500-selected-columns.csv",
            encoding=encoding
        )

        print(
            "Successfully loaded:",
            encoding
        )

        break

    except UnicodeDecodeError:

        print(
            "Failed:",
            encoding
        )

Successfully loaded: utf-8

CSV Delimiters

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',sep=",")
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',sep="|")
df.head()

  order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0  O100000,C17270,P234890,Home,164.08,0.15,1,Cred...
1  O100001,C17603,P228204,Grocery,24.73,0.0,1,Cre...
2  O100002,C10860,P213892,Electronics,175.58,0.05...
3  O100003,C15390,P208689,Electronics,63.67,0.0,1...
4  O100004,C15226,P228063,Home,16.33,0.15,1,COD,2...

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',sep="\t")
df.head()

  order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0  O100000,C17270,P234890,Home,164.08,0.15,1,Cred...
1  O100001,C17603,P228204,Grocery,24.73,0.0,1,Cre...
2  O100002,C10860,P213892,Electronics,175.58,0.05...
3  O100003,C15390,P208689,Electronics,63.67,0.0,1...
4  O100004,C15226,P228063,Home,16.33,0.15,1,COD,2...

Header Handling

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',header=0)
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9
0,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
1,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
2,O100001,C17603,P228204,Grocery,24.73,0.0,1,Credit Card,2025-04-03,6
3,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
4,O100003,C15390,P208689,Electronics,63.67,0.0,1,UPI,2024-09-14,6

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',header=0)
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            34500 non-null  object
 1   customer_id         34500 non-null  object
 2   product_id          34500 non-null  object
 3   category            34500 non-null  object
 4   price               34500 non-null  float64
 5   discount            34500 non-null  float64
 6   quantity            34500 non-null  int64
 7   payment_method      34500 non-null  object
 8   order_date          34500 non-null  object
 9   delivery_time_days  34500 non-null  int64
dtypes: float64(2), int64(2), object(6)
memory usage: 2.6+ MB

In [ ]:
df.columns = [
    "order_id",
    "customer_id",
    "product_id",
    "category",
    "price",
    "discount",
    "quantity",
    "payment_method",
    "order_date",
    "delivery_time_days"
]

In [ ]:
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
import pandas as pd

df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',
                 usecols=[
                     "order_id",
                     "customer_id",
                     "product_id",
                     "category",
                     "price",
                 ])

In [ ]:
df.head()

  order_id customer_id product_id     category   price
0  O100000      C17270    P234890         Home  164.08
1  O100001      C17603    P228204      Grocery   24.73
2  O100002      C10860    P213892  Electronics  175.58
3  O100003      C15390    P208689  Electronics   63.67
4  O100004      C15226    P228063         Home   16.33

In [ ]:
df = pd.read_csv(
    "/content/ecommerce_sales_34500-selected-columns.csv",
    dtype={
        "order_id":"object",
        "customer_id":"object",
        "product_id":"object",
        "price":"float32",
        "discount":"float32",
        "quantity":"int32",
        "delivery_time_days":"int32"
    }
)

In [ ]:
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.080002,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.730000,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.580002,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.669998,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.330000,0.15,1,COD,2024-12-21,6

Date Parsing

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',parse_dates=['order_date'])

In [ ]:
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

In [ ]:
df['order_date'].dtype

dtype('<M8[ns]')

In [ ]:
df = pd.read_csv(
    "/content/ecommerce_sales_34500-selected-columns.csv",
    na_values=[
        "NA",
        "Null",
        "NaN",
        "N/A",
        "missing",
        "-"
    ]
)

In [ ]:
df.isnull().sum()

order_id              0
customer_id           0
product_id            0
category              0
price                 0
discount              0
quantity              0
payment_method        0
order_date            0
delivery_time_days    0
dtype: int64

Low Memory

For large CSV files:

In [ ]:
df = pd.read_csv(
    '/content/ecommerce_sales_34500-selected-columns.csv',
    low_memory=False
)

Bad/Corrupt Records

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',on_bad_lines="skip")
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6

Read Only First 1000 Rows

In [ ]:
sample_df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',nrows=1000)

In [ ]:
sample_df.shape

(1000, 10)

Skip Rows

In [ ]:
df = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',skiprows=2)
df.head()

,O100001,C17603,P228204,Grocery,24.73,0.0,1,Credit Card,2025-04-03,6
0,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4
1,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6
2,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6
3,O100005,C15191,P214062,Beauty,53.91,0.10,2,Credit Card,2024-04-14,5
4,O100006,C13772,P201363,Electronics,266.50,0.00,1,PayPal,2025-05-20,5

LARGE CSV FILES

This is especially important for Data Engineering.

Suppose:

sales.csv

contains:

50 million rows

In [ ]:
chunks = pd.read_csv('/content/ecommerce_sales_34500-selected-columns.csv',chunksize=100000)

In [ ]:
for chunk in chunks:
  print(
      "Chunk Shape:",
      chunk.shape
  )

Chunk Shape: (34500, 10)

Process Each Chunk

In [ ]:
total_price = 0

for chunk in pd.read_csv(
    "/content/ecommerce_sales_34500-selected-columns.csv",
    chunksize=100000
):

    chunk_total = chunk["price"].sum()

    total_price += chunk_total

print(
    "Total Price:",
    total_price
)

Total Price: 4119011.32